#    _  ___ _ _            __   __
#   | |/ (_| | |           \ \ / /
#   | ' / _| | | ___ _ __   \ V /
#   |  < | | | |/ _ \ '__|   > <
#   | . \| | | |  __| |     / . \
#   |_|\_|_|_|_|\___|_|    /_/ \_\
#
# by Akari_my and TricolorAsp1209, for bugs contact us on Discord > akari_my, tricolorasp1209

# Configuration for the storage type
# Options: mysql, yml
Storage:
  type: mysql

Database:
  driver: com.mysql.cj.jdbc.Driver
  hostname: localhost
  port: 3306
  database:
  user:
  password:

# Message configuration
message:
  commands:
    setKills: "&7You set &e%value% Kills &7for &e%player%"
    setDeaths: "&7You set &e%value% Deaths &7for &e%player%"
    setStreak: "&7You set &e%value% Kill Streaks &7for &e%player%"
  errors:
    not_value: "&cPlease fill in all required values."
    player_not_found: "&cPlayer not found."
    console_sender: "&cThis command can only be used by players!"
    player_not_permission: "&cYou do not have permission to use this command."