#    _  ___ _ _            __   __
#   | |/ (_| | |           \ \ / /
#   | ' / _| | | ___ _ __   \ V /
#   |  < | | | |/ _ | '__|   > <
#   | . \| | | |  __| |     / . \
#   |_|\_|_|_|_|\___|_|    /_/ \_\
#
# by Akari_my and TricolorAsp1209, for bugs contact us on Discord > akari_my, tricolorasp1209

#
# Put your logins for the MySQL database
#
Database:
  driver: com.mysql.cj.jdbc.Driver
  hostname: localhost
  port: 3306
  database:
  user:
  password:

#
# Edit the message are inside the " "
# %player% = Player Name
# %value% = Value Count
#
message:
  commands:
    setKills: "&7You put &e%value% Kills &7on &e%player%"
    setDeaths: "&7You put &e%value% Deaths &7on &e%player%"
    setStreak: "&7You put &e%value% KillStreaks &7on &e%player%"
  errors:
    not_value: "&cFill in all missing values"
    player_not_found: "&cPlayer Not found"
    console_sender: "&cOnly players can use this command!"
    player_not_permession: "&cYou do not have permission to use this command"