name: KillerX
version: '${project.version}'
main: net.enderx.killerx.KillerX
api-version: '1.13'
authors: [Akari_my, TricolorAsp1209]
commands:
  killerx:
    description: ""
  stats:
    description: ""